[package]
name = "vtm_clan_quiz"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.5.1"

[build-dependencies]
slint-build = "1.5.1"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
